services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

#  spring-boot-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: spring_boot_app
#    environment:
#      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/rinha_db?authSource=admin
#    depends_on:
#      - mongodb
#    ports:
#      - "8080:8080"
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    driver: bridge

volumes:
  mongo_data:
    driver: local