services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: ./.env
    environment:
      MONGO_INITDB_DATABASE: rinha_db
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "500MB"
#
#  rabbitmq:
#    image: rabbitmq:3-management  # RabbitMQ com o plugin de gerenciamento
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"  # Porta padrão para conexões AMQP
#      - "15672:15672"  # Porta do painel de gerenciamento
#    environment:
#      RABBITMQ_DEFAULT_USER: guest  # Usuário padrão
#      RABBITMQ_DEFAULT_PASS: guest  # Senha padrão
#    volumes:
#      - rabbitmq-data:/var/lib/rabbitmq  # Persistência de dados

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${DB_USER}:${DB_PASS}@mongodb:27017/rinha_db?authSource=admin
    depends_on:
      - mongodb
    ports:
      - "8081:8080" # Mapeia a porta 8080 da instância para 8081 da máquina host
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app2
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${DB_USER}:${DB_PASS}@mongodb:27017/rinha_db?authSource=admin
    depends_on:
      - mongodb
    ports:
      - "8082:8080" # Mapeia a porta 8080 da segunda instância para 8082 da máquina host
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  rabbitmq-data: