spring:
  application:
    name: rinha-backend
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASS}@localhost:27017/rinha_db?authSource=admin
